spring:spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${google-client-id}
            client-secret: ${google.client-secret}
            scope:
              - profile
              - email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
          facebook:
            client-id: ${facebook-client-id}
            client-secret: ${facebook.client-secret}
            scope:
              - public_profile
              - email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
          amazon:
            client-id: ${amazon-client-id}
            client-secret: ${amazon.client-secret}
            scope:
              - email
              - profile
            redirect-uri: "{baseUrl}/login/oauth2/code/amazon"
            authorization-grant-type: authorization_code
          linkedin:
            client-id: ${linkedin-client-id}
            client-secret: ${linkedin.client-secret}
            scope:
              - r_liteprofile
              - r_emailaddress
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/linkedin"
            client-name: LinkedIn
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
          amazon:
            authorization-uri: https://www.amazon.com/ap/oa
            token-uri: https://api.amazon.com/auth/o2/token
            user-info-uri: https://api.amazon.com/user/profile
            user-name-attribute: user_id
          facebook:
            authorization-uri: https://www.facebook.com/v2.8/dialog/oauth
            token-uri: https://graph.facebook.com/v2.8/oauth/access_token
            user-info-uri: https://graph.facebook.com/me?fields=id,name,email
            user-name-attribute: id
          linkedin:
            authorization-uri: https://www.linkedin.com/oauth/v2/authorization
            token-uri: https://www.linkedin.com/oauth/v2/accessToken
            user-info-uri: https://api.linkedin.com/v2/me
            user-name-attribute: id
secrets:
  folder:
    path: /Users/ratnarijal/secrets/rijalClaude/app