spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 309175152276-khab09h2mp6p2unv19966qe233d2n8f2.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
            authorization-grant-type: authorization_code
          amazon:
            client-id: amzn1.application-oa2-client.8ac783e8facc4dd98e40992ff891a42e
            client-secret: amzn1.oa2-cs.v1.80510dda6302672500cf473caf8f06e1f599cd2d6896fda70ea686b1fadd58b9
            scope:
              - profile
            redirect-uri: "{baseUrl}/login/oauth2/code/amazon"
            authorization-grant-type: authorization_code
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
          amazon:
            authorization-uri: https://www.amazon.com/ap/oa
            token-uri: https://api.amazon.com/auth/o2/token
            user-info-uri: https://api.amazon.com/user/profile
            user-name-attribute: user_id
